// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/levels_update.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LevelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseAddress   []byte                 `protobuf:"bytes,1,opt,name=base_address,json=baseAddress,proto3" json:"base_address,omitempty"`
	BaseDecimals  uint32                 `protobuf:"varint,2,opt,name=base_decimals,json=baseDecimals,proto3" json:"base_decimals,omitempty"`
	QuoteAddress  []byte                 `protobuf:"bytes,3,opt,name=quote_address,json=quoteAddress,proto3" json:"quote_address,omitempty"`
	QuoteDecimals uint32                 `protobuf:"varint,4,opt,name=quote_decimals,json=quoteDecimals,proto3" json:"quote_decimals,omitempty"`
	Bids          []float64              `protobuf:"fixed64,5,rep,packed,name=bids,proto3" json:"bids,omitempty"` // [price, amount, price, amount, ...]
	Asks          []float64              `protobuf:"fixed64,6,rep,packed,name=asks,proto3" json:"asks,omitempty"` // [price, amount, price, amount, ...]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelInfo) Reset() {
	*x = LevelInfo{}
	mi := &file_proto_levels_update_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelInfo) ProtoMessage() {}

func (x *LevelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_levels_update_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelInfo.ProtoReflect.Descriptor instead.
func (*LevelInfo) Descriptor() ([]byte, []int) {
	return file_proto_levels_update_proto_rawDescGZIP(), []int{0}
}

func (x *LevelInfo) GetBaseAddress() []byte {
	if x != nil {
		return x.BaseAddress
	}
	return nil
}

func (x *LevelInfo) GetBaseDecimals() uint32 {
	if x != nil {
		return x.BaseDecimals
	}
	return 0
}

func (x *LevelInfo) GetQuoteAddress() []byte {
	if x != nil {
		return x.QuoteAddress
	}
	return nil
}

func (x *LevelInfo) GetQuoteDecimals() uint32 {
	if x != nil {
		return x.QuoteDecimals
	}
	return 0
}

func (x *LevelInfo) GetBids() []float64 {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *LevelInfo) GetAsks() []float64 {
	if x != nil {
		return x.Asks
	}
	return nil
}

type LevelMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Levels        []*LevelInfo           `protobuf:"bytes,1,rep,name=levels,proto3" json:"levels,omitempty"`
	MakerAddress  []byte                 `protobuf:"bytes,2,opt,name=maker_address,json=makerAddress,proto3" json:"maker_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelMsg) Reset() {
	*x = LevelMsg{}
	mi := &file_proto_levels_update_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelMsg) ProtoMessage() {}

func (x *LevelMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_levels_update_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelMsg.ProtoReflect.Descriptor instead.
func (*LevelMsg) Descriptor() ([]byte, []int) {
	return file_proto_levels_update_proto_rawDescGZIP(), []int{1}
}

func (x *LevelMsg) GetLevels() []*LevelInfo {
	if x != nil {
		return x.Levels
	}
	return nil
}

func (x *LevelMsg) GetMakerAddress() []byte {
	if x != nil {
		return x.MakerAddress
	}
	return nil
}

type LevelsSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint32                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	MsgTopic      string                 `protobuf:"bytes,2,opt,name=msg_topic,json=msgTopic,proto3" json:"msg_topic,omitempty"` // pricing
	MsgType       string                 `protobuf:"bytes,3,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`    // update
	Msg           *LevelMsg              `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelsSchema) Reset() {
	*x = LevelsSchema{}
	mi := &file_proto_levels_update_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelsSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelsSchema) ProtoMessage() {}

func (x *LevelsSchema) ProtoReflect() protoreflect.Message {
	mi := &file_proto_levels_update_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelsSchema.ProtoReflect.Descriptor instead.
func (*LevelsSchema) Descriptor() ([]byte, []int) {
	return file_proto_levels_update_proto_rawDescGZIP(), []int{2}
}

func (x *LevelsSchema) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *LevelsSchema) GetMsgTopic() string {
	if x != nil {
		return x.MsgTopic
	}
	return ""
}

func (x *LevelsSchema) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *LevelsSchema) GetMsg() *LevelMsg {
	if x != nil {
		return x.Msg
	}
	return nil
}

var File_proto_levels_update_proto protoreflect.FileDescriptor

const file_proto_levels_update_proto_rawDesc = "" +
	"\n" +
	"\x19proto/levels_update.proto\x12\x05bebop\"\xcf\x01\n" +
	"\tLevelInfo\x12!\n" +
	"\fbase_address\x18\x01 \x01(\fR\vbaseAddress\x12#\n" +
	"\rbase_decimals\x18\x02 \x01(\rR\fbaseDecimals\x12#\n" +
	"\rquote_address\x18\x03 \x01(\fR\fquoteAddress\x12%\n" +
	"\x0equote_decimals\x18\x04 \x01(\rR\rquoteDecimals\x12\x16\n" +
	"\x04bids\x18\x05 \x03(\x01B\x02\x10\x01R\x04bids\x12\x16\n" +
	"\x04asks\x18\x06 \x03(\x01B\x02\x10\x01R\x04asks\"Y\n" +
	"\bLevelMsg\x12(\n" +
	"\x06levels\x18\x01 \x03(\v2\x10.bebop.LevelInfoR\x06levels\x12#\n" +
	"\rmaker_address\x18\x02 \x01(\fR\fmakerAddress\"\x84\x01\n" +
	"\fLevelsSchema\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\rR\achainId\x12\x1b\n" +
	"\tmsg_topic\x18\x02 \x01(\tR\bmsgTopic\x12\x19\n" +
	"\bmsg_type\x18\x03 \x01(\tR\amsgType\x12!\n" +
	"\x03msg\x18\x04 \x01(\v2\x0f.bebop.LevelMsgR\x03msgB\rZ\vbebop/protob\x06proto3"

var (
	file_proto_levels_update_proto_rawDescOnce sync.Once
	file_proto_levels_update_proto_rawDescData []byte
)

func file_proto_levels_update_proto_rawDescGZIP() []byte {
	file_proto_levels_update_proto_rawDescOnce.Do(func() {
		file_proto_levels_update_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_levels_update_proto_rawDesc), len(file_proto_levels_update_proto_rawDesc)))
	})
	return file_proto_levels_update_proto_rawDescData
}

var file_proto_levels_update_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_levels_update_proto_goTypes = []any{
	(*LevelInfo)(nil),    // 0: bebop.LevelInfo
	(*LevelMsg)(nil),     // 1: bebop.LevelMsg
	(*LevelsSchema)(nil), // 2: bebop.LevelsSchema
}
var file_proto_levels_update_proto_depIdxs = []int32{
	0, // 0: bebop.LevelMsg.levels:type_name -> bebop.LevelInfo
	1, // 1: bebop.LevelsSchema.msg:type_name -> bebop.LevelMsg
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_levels_update_proto_init() }
func file_proto_levels_update_proto_init() {
	if File_proto_levels_update_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_levels_update_proto_rawDesc), len(file_proto_levels_update_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_levels_update_proto_goTypes,
		DependencyIndexes: file_proto_levels_update_proto_depIdxs,
		MessageInfos:      file_proto_levels_update_proto_msgTypes,
	}.Build()
	File_proto_levels_update_proto = out.File
	file_proto_levels_update_proto_goTypes = nil
	file_proto_levels_update_proto_depIdxs = nil
}
