// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/rfq_messages.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Root message to encompass all trade and quote-related messages
type CombinedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeUpdate   *TradeUpdate           `protobuf:"bytes,1,opt,name=trade_update,json=tradeUpdate,proto3" json:"trade_update,omitempty"`
	QuoteRequest  *QuoteRequest          `protobuf:"bytes,2,opt,name=quote_request,json=quoteRequest,proto3" json:"quote_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombinedMessage) Reset() {
	*x = CombinedMessage{}
	mi := &file_proto_rfq_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombinedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombinedMessage) ProtoMessage() {}

func (x *CombinedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rfq_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombinedMessage.ProtoReflect.Descriptor instead.
func (*CombinedMessage) Descriptor() ([]byte, []int) {
	return file_proto_rfq_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CombinedMessage) GetTradeUpdate() *TradeUpdate {
	if x != nil {
		return x.TradeUpdate
	}
	return nil
}

func (x *CombinedMessage) GetQuoteRequest() *QuoteRequest {
	if x != nil {
		return x.QuoteRequest
	}
	return nil
}

type TradeUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint32                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	MsgTopic      string                 `protobuf:"bytes,2,opt,name=msg_topic,json=msgTopic,proto3" json:"msg_topic,omitempty"`
	MsgType       string                 `protobuf:"bytes,3,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Msg           *TradeMessage          `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeUpdate) Reset() {
	*x = TradeUpdate{}
	mi := &file_proto_rfq_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeUpdate) ProtoMessage() {}

func (x *TradeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rfq_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeUpdate.ProtoReflect.Descriptor instead.
func (*TradeUpdate) Descriptor() ([]byte, []int) {
	return file_proto_rfq_messages_proto_rawDescGZIP(), []int{1}
}

func (x *TradeUpdate) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *TradeUpdate) GetMsgTopic() string {
	if x != nil {
		return x.MsgTopic
	}
	return ""
}

func (x *TradeUpdate) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *TradeUpdate) GetMsg() *TradeMessage {
	if x != nil {
		return x.Msg
	}
	return nil
}

type TradeMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	QuoteId          string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	TxHash           string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Executor         string                 `protobuf:"bytes,3,opt,name=executor,proto3" json:"executor,omitempty"` // 'bebop' for gasless, 'taker' for self-execution
	EventId          string                 `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	OrderTime        int64                  `protobuf:"varint,6,opt,name=order_time,json=orderTime,proto3" json:"order_time,omitempty"` // UNIX timestamp in nanoseconds
	FeeNative        float64                `protobuf:"fixed64,7,opt,name=fee_native,json=feeNative,proto3" json:"fee_native,omitempty"`
	Surplus          float64                `protobuf:"fixed64,8,opt,name=surplus,proto3" json:"surplus,omitempty"` // In native token
	SurplusRecipient string                 `protobuf:"bytes,9,opt,name=surplus_recipient,json=surplusRecipient,proto3" json:"surplus_recipient,omitempty"`
	PrevQuoteId      string                 `protobuf:"bytes,10,opt,name=prev_quote_id,json=prevQuoteId,proto3" json:"prev_quote_id,omitempty"`
	Quotes           []*Quote               `protobuf:"bytes,11,rep,name=quotes,proto3" json:"quotes,omitempty"`
	PrevQuotes       []*Quote               `protobuf:"bytes,12,rep,name=prev_quotes,json=prevQuotes,proto3" json:"prev_quotes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TradeMessage) Reset() {
	*x = TradeMessage{}
	mi := &file_proto_rfq_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeMessage) ProtoMessage() {}

func (x *TradeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rfq_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeMessage.ProtoReflect.Descriptor instead.
func (*TradeMessage) Descriptor() ([]byte, []int) {
	return file_proto_rfq_messages_proto_rawDescGZIP(), []int{2}
}

func (x *TradeMessage) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *TradeMessage) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TradeMessage) GetExecutor() string {
	if x != nil {
		return x.Executor
	}
	return ""
}

func (x *TradeMessage) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TradeMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TradeMessage) GetOrderTime() int64 {
	if x != nil {
		return x.OrderTime
	}
	return 0
}

func (x *TradeMessage) GetFeeNative() float64 {
	if x != nil {
		return x.FeeNative
	}
	return 0
}

func (x *TradeMessage) GetSurplus() float64 {
	if x != nil {
		return x.Surplus
	}
	return 0
}

func (x *TradeMessage) GetSurplusRecipient() string {
	if x != nil {
		return x.SurplusRecipient
	}
	return ""
}

func (x *TradeMessage) GetPrevQuoteId() string {
	if x != nil {
		return x.PrevQuoteId
	}
	return ""
}

func (x *TradeMessage) GetQuotes() []*Quote {
	if x != nil {
		return x.Quotes
	}
	return nil
}

func (x *TradeMessage) GetPrevQuotes() []*Quote {
	if x != nil {
		return x.PrevQuotes
	}
	return nil
}

type Quote struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TakerToken        string                 `protobuf:"bytes,1,opt,name=taker_token,json=takerToken,proto3" json:"taker_token,omitempty"`
	TakerAmount       string                 `protobuf:"bytes,2,opt,name=taker_amount,json=takerAmount,proto3" json:"taker_amount,omitempty"` // In smallest units (e.g., wei)
	MakerToken        string                 `protobuf:"bytes,3,opt,name=maker_token,json=makerToken,proto3" json:"maker_token,omitempty"`
	MakerAmount       string                 `protobuf:"bytes,4,opt,name=maker_amount,json=makerAmount,proto3" json:"maker_amount,omitempty"` // In smallest units (e.g., wei)
	FilledTakerAmount string                 `protobuf:"bytes,5,opt,name=filled_taker_amount,json=filledTakerAmount,proto3" json:"filled_taker_amount,omitempty"`
	FilledMakerAmount string                 `protobuf:"bytes,6,opt,name=filled_maker_amount,json=filledMakerAmount,proto3" json:"filled_maker_amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_proto_rfq_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rfq_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_proto_rfq_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Quote) GetTakerToken() string {
	if x != nil {
		return x.TakerToken
	}
	return ""
}

func (x *Quote) GetTakerAmount() string {
	if x != nil {
		return x.TakerAmount
	}
	return ""
}

func (x *Quote) GetMakerToken() string {
	if x != nil {
		return x.MakerToken
	}
	return ""
}

func (x *Quote) GetMakerAmount() string {
	if x != nil {
		return x.MakerAmount
	}
	return ""
}

func (x *Quote) GetFilledTakerAmount() string {
	if x != nil {
		return x.FilledTakerAmount
	}
	return ""
}

func (x *Quote) GetFilledMakerAmount() string {
	if x != nil {
		return x.FilledMakerAmount
	}
	return ""
}

type QuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint32                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	MsgTopic      string                 `protobuf:"bytes,2,opt,name=msg_topic,json=msgTopic,proto3" json:"msg_topic,omitempty"`
	MsgType       string                 `protobuf:"bytes,3,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Msg           *QuoteMessage          `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	mi := &file_proto_rfq_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rfq_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_rfq_messages_proto_rawDescGZIP(), []int{4}
}

func (x *QuoteRequest) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *QuoteRequest) GetMsgTopic() string {
	if x != nil {
		return x.MsgTopic
	}
	return ""
}

func (x *QuoteRequest) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *QuoteRequest) GetMsg() *QuoteMessage {
	if x != nil {
		return x.Msg
	}
	return nil
}

type QuoteMessage struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	QuoteId            string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	EventId            string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OrderSigningType   string                 `protobuf:"bytes,3,opt,name=order_signing_type,json=orderSigningType,proto3" json:"order_signing_type,omitempty"`
	OrderType          string                 `protobuf:"bytes,4,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	OnchainPartnerId   uint32                 `protobuf:"varint,5,opt,name=onchain_partner_id,json=onchainPartnerId,proto3" json:"onchain_partner_id,omitempty"`
	Expiry             int64                  `protobuf:"varint,6,opt,name=expiry,proto3" json:"expiry,omitempty"` // UNIX timestamp
	TakerAddress       string                 `protobuf:"bytes,7,opt,name=taker_address,json=takerAddress,proto3" json:"taker_address,omitempty"`
	OriginAddress      string                 `protobuf:"bytes,8,opt,name=origin_address,json=originAddress,proto3" json:"origin_address,omitempty"`
	MakerAddress       string                 `protobuf:"bytes,9,opt,name=maker_address,json=makerAddress,proto3" json:"maker_address,omitempty"` // This can be null, handle as optional
	MakerNonce         string                 `protobuf:"bytes,10,opt,name=maker_nonce,json=makerNonce,proto3" json:"maker_nonce,omitempty"`
	Quotes             []*Quote               `protobuf:"bytes,11,rep,name=quotes,proto3" json:"quotes,omitempty"`
	Receiver           string                 `protobuf:"bytes,12,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Commands           string                 `protobuf:"bytes,13,opt,name=commands,proto3" json:"commands,omitempty"`
	PackedCommands     uint32                 `protobuf:"varint,14,opt,name=packed_commands,json=packedCommands,proto3" json:"packed_commands,omitempty"`
	FeeNative          float64                `protobuf:"fixed64,15,opt,name=fee_native,json=feeNative,proto3" json:"fee_native,omitempty"`
	TakerTokens        []string               `protobuf:"bytes,16,rep,name=taker_tokens,json=takerTokens,proto3" json:"taker_tokens,omitempty"`
	MakerTokens        []string               `protobuf:"bytes,17,rep,name=maker_tokens,json=makerTokens,proto3" json:"maker_tokens,omitempty"`
	TakerTokensIndices []int32                `protobuf:"varint,18,rep,packed,name=taker_tokens_indices,json=takerTokensIndices,proto3" json:"taker_tokens_indices,omitempty"`
	MakerTokensIndices []int32                `protobuf:"varint,19,rep,packed,name=maker_tokens_indices,json=makerTokensIndices,proto3" json:"maker_tokens_indices,omitempty"`
	IsAggregateOrder   bool                   `protobuf:"varint,20,opt,name=is_aggregate_order,json=isAggregateOrder,proto3" json:"is_aggregate_order,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QuoteMessage) Reset() {
	*x = QuoteMessage{}
	mi := &file_proto_rfq_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteMessage) ProtoMessage() {}

func (x *QuoteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rfq_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteMessage.ProtoReflect.Descriptor instead.
func (*QuoteMessage) Descriptor() ([]byte, []int) {
	return file_proto_rfq_messages_proto_rawDescGZIP(), []int{5}
}

func (x *QuoteMessage) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *QuoteMessage) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *QuoteMessage) GetOrderSigningType() string {
	if x != nil {
		return x.OrderSigningType
	}
	return ""
}

func (x *QuoteMessage) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *QuoteMessage) GetOnchainPartnerId() uint32 {
	if x != nil {
		return x.OnchainPartnerId
	}
	return 0
}

func (x *QuoteMessage) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *QuoteMessage) GetTakerAddress() string {
	if x != nil {
		return x.TakerAddress
	}
	return ""
}

func (x *QuoteMessage) GetOriginAddress() string {
	if x != nil {
		return x.OriginAddress
	}
	return ""
}

func (x *QuoteMessage) GetMakerAddress() string {
	if x != nil {
		return x.MakerAddress
	}
	return ""
}

func (x *QuoteMessage) GetMakerNonce() string {
	if x != nil {
		return x.MakerNonce
	}
	return ""
}

func (x *QuoteMessage) GetQuotes() []*Quote {
	if x != nil {
		return x.Quotes
	}
	return nil
}

func (x *QuoteMessage) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *QuoteMessage) GetCommands() string {
	if x != nil {
		return x.Commands
	}
	return ""
}

func (x *QuoteMessage) GetPackedCommands() uint32 {
	if x != nil {
		return x.PackedCommands
	}
	return 0
}

func (x *QuoteMessage) GetFeeNative() float64 {
	if x != nil {
		return x.FeeNative
	}
	return 0
}

func (x *QuoteMessage) GetTakerTokens() []string {
	if x != nil {
		return x.TakerTokens
	}
	return nil
}

func (x *QuoteMessage) GetMakerTokens() []string {
	if x != nil {
		return x.MakerTokens
	}
	return nil
}

func (x *QuoteMessage) GetTakerTokensIndices() []int32 {
	if x != nil {
		return x.TakerTokensIndices
	}
	return nil
}

func (x *QuoteMessage) GetMakerTokensIndices() []int32 {
	if x != nil {
		return x.MakerTokensIndices
	}
	return nil
}

func (x *QuoteMessage) GetIsAggregateOrder() bool {
	if x != nil {
		return x.IsAggregateOrder
	}
	return false
}

var File_proto_rfq_messages_proto protoreflect.FileDescriptor

const file_proto_rfq_messages_proto_rawDesc = "" +
	"\n" +
	"\x18proto/rfq_messages.proto\x12\x05bebop\"\x82\x01\n" +
	"\x0fCombinedMessage\x125\n" +
	"\ftrade_update\x18\x01 \x01(\v2\x12.bebop.TradeUpdateR\vtradeUpdate\x128\n" +
	"\rquote_request\x18\x02 \x01(\v2\x13.bebop.QuoteRequestR\fquoteRequest\"\x87\x01\n" +
	"\vTradeUpdate\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\rR\achainId\x12\x1b\n" +
	"\tmsg_topic\x18\x02 \x01(\tR\bmsgTopic\x12\x19\n" +
	"\bmsg_type\x18\x03 \x01(\tR\amsgType\x12%\n" +
	"\x03msg\x18\x04 \x01(\v2\x13.bebop.TradeMessageR\x03msg\"\x8f\x03\n" +
	"\fTradeMessage\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12\x1a\n" +
	"\bexecutor\x18\x03 \x01(\tR\bexecutor\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\tR\aeventId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"order_time\x18\x06 \x01(\x03R\torderTime\x12\x1d\n" +
	"\n" +
	"fee_native\x18\a \x01(\x01R\tfeeNative\x12\x18\n" +
	"\asurplus\x18\b \x01(\x01R\asurplus\x12+\n" +
	"\x11surplus_recipient\x18\t \x01(\tR\x10surplusRecipient\x12\"\n" +
	"\rprev_quote_id\x18\n" +
	" \x01(\tR\vprevQuoteId\x12$\n" +
	"\x06quotes\x18\v \x03(\v2\f.bebop.QuoteR\x06quotes\x12-\n" +
	"\vprev_quotes\x18\f \x03(\v2\f.bebop.QuoteR\n" +
	"prevQuotes\"\xef\x01\n" +
	"\x05Quote\x12\x1f\n" +
	"\vtaker_token\x18\x01 \x01(\tR\n" +
	"takerToken\x12!\n" +
	"\ftaker_amount\x18\x02 \x01(\tR\vtakerAmount\x12\x1f\n" +
	"\vmaker_token\x18\x03 \x01(\tR\n" +
	"makerToken\x12!\n" +
	"\fmaker_amount\x18\x04 \x01(\tR\vmakerAmount\x12.\n" +
	"\x13filled_taker_amount\x18\x05 \x01(\tR\x11filledTakerAmount\x12.\n" +
	"\x13filled_maker_amount\x18\x06 \x01(\tR\x11filledMakerAmount\"\x88\x01\n" +
	"\fQuoteRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\rR\achainId\x12\x1b\n" +
	"\tmsg_topic\x18\x02 \x01(\tR\bmsgTopic\x12\x19\n" +
	"\bmsg_type\x18\x03 \x01(\tR\amsgType\x12%\n" +
	"\x03msg\x18\x04 \x01(\v2\x13.bebop.QuoteMessageR\x03msg\"\xe7\x05\n" +
	"\fQuoteMessage\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12,\n" +
	"\x12order_signing_type\x18\x03 \x01(\tR\x10orderSigningType\x12\x1d\n" +
	"\n" +
	"order_type\x18\x04 \x01(\tR\torderType\x12,\n" +
	"\x12onchain_partner_id\x18\x05 \x01(\rR\x10onchainPartnerId\x12\x16\n" +
	"\x06expiry\x18\x06 \x01(\x03R\x06expiry\x12#\n" +
	"\rtaker_address\x18\a \x01(\tR\ftakerAddress\x12%\n" +
	"\x0eorigin_address\x18\b \x01(\tR\roriginAddress\x12#\n" +
	"\rmaker_address\x18\t \x01(\tR\fmakerAddress\x12\x1f\n" +
	"\vmaker_nonce\x18\n" +
	" \x01(\tR\n" +
	"makerNonce\x12$\n" +
	"\x06quotes\x18\v \x03(\v2\f.bebop.QuoteR\x06quotes\x12\x1a\n" +
	"\breceiver\x18\f \x01(\tR\breceiver\x12\x1a\n" +
	"\bcommands\x18\r \x01(\tR\bcommands\x12'\n" +
	"\x0fpacked_commands\x18\x0e \x01(\rR\x0epackedCommands\x12\x1d\n" +
	"\n" +
	"fee_native\x18\x0f \x01(\x01R\tfeeNative\x12!\n" +
	"\ftaker_tokens\x18\x10 \x03(\tR\vtakerTokens\x12!\n" +
	"\fmaker_tokens\x18\x11 \x03(\tR\vmakerTokens\x120\n" +
	"\x14taker_tokens_indices\x18\x12 \x03(\x05R\x12takerTokensIndices\x120\n" +
	"\x14maker_tokens_indices\x18\x13 \x03(\x05R\x12makerTokensIndices\x12,\n" +
	"\x12is_aggregate_order\x18\x14 \x01(\bR\x10isAggregateOrderB\rZ\vbebop/protob\x06proto3"

var (
	file_proto_rfq_messages_proto_rawDescOnce sync.Once
	file_proto_rfq_messages_proto_rawDescData []byte
)

func file_proto_rfq_messages_proto_rawDescGZIP() []byte {
	file_proto_rfq_messages_proto_rawDescOnce.Do(func() {
		file_proto_rfq_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rfq_messages_proto_rawDesc), len(file_proto_rfq_messages_proto_rawDesc)))
	})
	return file_proto_rfq_messages_proto_rawDescData
}

var file_proto_rfq_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_rfq_messages_proto_goTypes = []any{
	(*CombinedMessage)(nil), // 0: bebop.CombinedMessage
	(*TradeUpdate)(nil),     // 1: bebop.TradeUpdate
	(*TradeMessage)(nil),    // 2: bebop.TradeMessage
	(*Quote)(nil),           // 3: bebop.Quote
	(*QuoteRequest)(nil),    // 4: bebop.QuoteRequest
	(*QuoteMessage)(nil),    // 5: bebop.QuoteMessage
}
var file_proto_rfq_messages_proto_depIdxs = []int32{
	1, // 0: bebop.CombinedMessage.trade_update:type_name -> bebop.TradeUpdate
	4, // 1: bebop.CombinedMessage.quote_request:type_name -> bebop.QuoteRequest
	2, // 2: bebop.TradeUpdate.msg:type_name -> bebop.TradeMessage
	3, // 3: bebop.TradeMessage.quotes:type_name -> bebop.Quote
	3, // 4: bebop.TradeMessage.prev_quotes:type_name -> bebop.Quote
	5, // 5: bebop.QuoteRequest.msg:type_name -> bebop.QuoteMessage
	3, // 6: bebop.QuoteMessage.quotes:type_name -> bebop.Quote
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_rfq_messages_proto_init() }
func file_proto_rfq_messages_proto_init() {
	if File_proto_rfq_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rfq_messages_proto_rawDesc), len(file_proto_rfq_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_rfq_messages_proto_goTypes,
		DependencyIndexes: file_proto_rfq_messages_proto_depIdxs,
		MessageInfos:      file_proto_rfq_messages_proto_msgTypes,
	}.Build()
	File_proto_rfq_messages_proto = out.File
	file_proto_rfq_messages_proto_goTypes = nil
	file_proto_rfq_messages_proto_depIdxs = nil
}
