// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/websocket_response.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebSocketMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Reason        *string                `protobuf:"bytes,3,opt,name=reason,proto3,oneof" json:"reason,omitempty"` // used for error messages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketMsg) Reset() {
	*x = WebSocketMsg{}
	mi := &file_proto_websocket_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketMsg) ProtoMessage() {}

func (x *WebSocketMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketMsg.ProtoReflect.Descriptor instead.
func (*WebSocketMsg) Descriptor() ([]byte, []int) {
	return file_proto_websocket_response_proto_rawDescGZIP(), []int{0}
}

func (x *WebSocketMsg) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WebSocketMsg) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *WebSocketMsg) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type WebSocketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint32                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	MsgTopic      string                 `protobuf:"bytes,2,opt,name=msg_topic,json=msgTopic,proto3" json:"msg_topic,omitempty"`
	MsgType       string                 `protobuf:"bytes,3,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Msg           *WebSocketMsg          `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketResponse) Reset() {
	*x = WebSocketResponse{}
	mi := &file_proto_websocket_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketResponse) ProtoMessage() {}

func (x *WebSocketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_websocket_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketResponse.ProtoReflect.Descriptor instead.
func (*WebSocketResponse) Descriptor() ([]byte, []int) {
	return file_proto_websocket_response_proto_rawDescGZIP(), []int{1}
}

func (x *WebSocketResponse) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *WebSocketResponse) GetMsgTopic() string {
	if x != nil {
		return x.MsgTopic
	}
	return ""
}

func (x *WebSocketResponse) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *WebSocketResponse) GetMsg() *WebSocketMsg {
	if x != nil {
		return x.Msg
	}
	return nil
}

var File_proto_websocket_response_proto protoreflect.FileDescriptor

const file_proto_websocket_response_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/websocket_response.proto\x12\x05bebop\"^\n" +
	"\fWebSocketMsg\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1b\n" +
	"\x06reason\x18\x03 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"\x8d\x01\n" +
	"\x11WebSocketResponse\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\rR\achainId\x12\x1b\n" +
	"\tmsg_topic\x18\x02 \x01(\tR\bmsgTopic\x12\x19\n" +
	"\bmsg_type\x18\x03 \x01(\tR\amsgType\x12%\n" +
	"\x03msg\x18\x04 \x01(\v2\x13.bebop.WebSocketMsgR\x03msgB\rZ\vbebop/protob\x06proto3"

var (
	file_proto_websocket_response_proto_rawDescOnce sync.Once
	file_proto_websocket_response_proto_rawDescData []byte
)

func file_proto_websocket_response_proto_rawDescGZIP() []byte {
	file_proto_websocket_response_proto_rawDescOnce.Do(func() {
		file_proto_websocket_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_websocket_response_proto_rawDesc), len(file_proto_websocket_response_proto_rawDesc)))
	})
	return file_proto_websocket_response_proto_rawDescData
}

var file_proto_websocket_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_websocket_response_proto_goTypes = []any{
	(*WebSocketMsg)(nil),      // 0: bebop.WebSocketMsg
	(*WebSocketResponse)(nil), // 1: bebop.WebSocketResponse
}
var file_proto_websocket_response_proto_depIdxs = []int32{
	0, // 0: bebop.WebSocketResponse.msg:type_name -> bebop.WebSocketMsg
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_websocket_response_proto_init() }
func file_proto_websocket_response_proto_init() {
	if File_proto_websocket_response_proto != nil {
		return
	}
	file_proto_websocket_response_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_websocket_response_proto_rawDesc), len(file_proto_websocket_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_websocket_response_proto_goTypes,
		DependencyIndexes: file_proto_websocket_response_proto_depIdxs,
		MessageInfos:      file_proto_websocket_response_proto_msgTypes,
	}.Build()
	File_proto_websocket_response_proto = out.File
	file_proto_websocket_response_proto_goTypes = nil
	file_proto_websocket_response_proto_depIdxs = nil
}
